### ISSUE TITLE
typo in the command to run the webapp

### ISSUE THREAD

**Issue by earthfail** [practicalli/banking-on-clojure-webapp#1]
Hi, in the README.md it says (line 24)

> clojure -m practicalli.banking-on-clojure-webapp

but it should be

> clojure -m practicalli.banking-on-clojure

to match the current path for the file the includes -main function.
other links are "clojure-webapp" instead of "clojure" so I think the namespace was changed in the file
but not anywhere else.

**Comment by jr0cket** [comment]
Thank you for spotting this.  I used the GitHub repo name rather than the namespace.

I've also updated the command line for the latest version of Clojure CLI tools.
